function SelectCity(county){
	var count=0;
	if(county){	
		alert(county);
	switch(county){
	
			case '01':
				removeAllOptions(document.getElementById('city'));
				addOption(document.getElementById('city'),"All", "ALL");
				addOption(document.getElementById('city'),"00","UNINCORPORATED");
				addOption(document.getElementById('city'),"01","ALAMEDA");
				addOption(document.getElementById('city'),"02","ALBANY");
				addOption(document.getElementById('city'),"03","BERKELEY");
				addOption(document.getElementById('city'),"04","EMERYVILLE");
				addOption(document.getElementById('city'),"05","FREMONT");
				addOption(document.getElementById('city'),"06","HAYWARD");
				addOption(document.getElementById('city'),"07","LIVERMORE");
				addOption(document.getElementById('city'),"08","NEWARK");
				addOption(document.getElementById('city'),"09","OAKLAND");
				addOption(document.getElementById('city'),"10","PIEDMONT");
				addOption(document.getElementById('city'),"11","PLEASANTON");
				addOption(document.getElementById('city'),"12","SAN LEANDRO");
				addOption(document.getElementById('city'),"13","UNION CITY");
				addOption(document.getElementById('city'),"15","CSU HAYWARD");
				addOption(document.getElementById('city'),"22","UC LIVERMORE LAB");
				addOption(document.getElementById('city'),"41","OAKLAND INTL AIRPORT");
				addOption(document.getElementById('city'),"97","UC BERKELEY");
				addOption(document.getElementById('city'),"98","DUBLIN");
			break;
			case '02':
				removeAllOptions(document.getElementById('city'));
				addOption(document.getElementById('city'),"All", "ALL");
				addOption(document.getElementById('city'),"00","UNINCORPORATED");
			break;
			case '03':
				removeAllOptions(document.getElementById('city'));
				addOption(document.getElementById('city'),"All", "ALL");
				addOption(document.getElementById('city'),"00","UNINCORPORATED");
				addOption(document.getElementById('city'),"01","AMADOR CITY");
				addOption(document.getElementById('city'),"02","IONE");
				addOption(document.getElementById('city'),"03","JACKSON");
				addOption(document.getElementById('city'),"04","PLYMOUTH");
				addOption(document.getElementById('city'),"05","SUTTER CREEK");
			break;
			case '04':
				removeAllOptions(document.getElementById('city'));
				addOption(document.getElementById('city'),"All", "ALL");
				addOption(document.getElementById('city'),"00","UNINCORPORATED");
				addOption(document.getElementById('city'),"01","BIGGS");
				addOption(document.getElementById('city'),"02","CHICO");
				addOption(document.getElementById('city'),"03","GRIDLEY");
				addOption(document.getElementById('city'),"04","OROVILLE");
				addOption(document.getElementById('city'),"05","PARADISE");
				addOption(document.getElementById('city'),"07","NORTHERN BUTTE DIST");
				addOption(document.getElementById('city'),"97","CSU CHICO");
			break;
			case '05':
				removeAllOptions(document.getElementById('city'));
				addOption(document.getElementById('city'),"All", "ALL");
				addOption(document.getElementById('city'),"00","UNINCORPORATED");
				addOption(document.getElementById('city'),"01","ANGELS CAMP");
				addOption(document.getElementById('city'),"03","CALAVERAS PARK DIST");
			break;
			case '06':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","COLUSA");
addOption(document.getElementById('city'),"02","WILLIAMS");
break;case '07':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","ANTIOCH");
addOption(document.getElementById('city'),"02","BRENTWOOD");
addOption(document.getElementById('city'),"03","CLAYTON");
addOption(document.getElementById('city'),"04","CONCORD");
addOption(document.getElementById('city'),"05","EL CERRITO");
addOption(document.getElementById('city'),"06","HERCULES");
addOption(document.getElementById('city'),"07","PINOLE");
addOption(document.getElementById('city'),"08","PITTSBURG");
addOption(document.getElementById('city'),"09","PLEASANT HILL");
addOption(document.getElementById('city'),"10","RICHMOND");
addOption(document.getElementById('city'),"11","SAN PABLO");
addOption(document.getElementById('city'),"12","WALNUT CREEK");
addOption(document.getElementById('city'),"13","KENSINGTON");
addOption(document.getElementById('city'),"14","MARTINEZ");
addOption(document.getElementById('city'),"15","LAFAYETTE");
addOption(document.getElementById('city'),"16","MORAGA");
addOption(document.getElementById('city'),"34","OAKLEY");
addOption(document.getElementById('city'),"90","DANVILLE");
addOption(document.getElementById('city'),"91","SAN RAMON");
addOption(document.getElementById('city'),"92","ORINDA");
break;case '08':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","CRESCENT CITY");
break;case '09':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","PLACERVILLE");
addOption(document.getElementById('city'),"02","SOUTH LAKE TAHOE");
break;case '10':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","CLOVIS");
addOption(document.getElementById('city'),"02","COALINGA");
addOption(document.getElementById('city'),"03","FIREBAUGH");
addOption(document.getElementById('city'),"04","FOWLER");
addOption(document.getElementById('city'),"05","FRESNO");
addOption(document.getElementById('city'),"06","HURON");
addOption(document.getElementById('city'),"07","KERMAN");
addOption(document.getElementById('city'),"08","KINGSBURG");
addOption(document.getElementById('city'),"09","MENDOTA");
addOption(document.getElementById('city'),"10","ORANGE COVE");
addOption(document.getElementById('city'),"11","PARLIER");
addOption(document.getElementById('city'),"12","REEDLEY");
addOption(document.getElementById('city'),"13","SANGER");
addOption(document.getElementById('city'),"14","SAN JOAQUIN");
addOption(document.getElementById('city'),"15","SELMA");
addOption(document.getElementById('city'),"30","SAN JOAQUIN VLY DIST");
addOption(document.getElementById('city'),"97","CSU FRESNO");
break;case '11':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","ORLAND");
addOption(document.getElementById('city'),"02","WILLOWS");
break;case '12':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","ARCATA");
addOption(document.getElementById('city'),"02","BLUE LAKE");
addOption(document.getElementById('city'),"03","EUREKA");
addOption(document.getElementById('city'),"04","FERNDALE");
addOption(document.getElementById('city'),"05","FORTUNA");
addOption(document.getElementById('city'),"06","TRINIDAD");
addOption(document.getElementById('city'),"07","RIO DELL");
addOption(document.getElementById('city'),"08","HUMBOLDT STATE UNIV");
addOption(document.getElementById('city'),"11","NO CST REDWOOD DIST");
break;case '13':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","BRAWLEY");
addOption(document.getElementById('city'),"02","CALEXICO");
addOption(document.getElementById('city'),"03","CALIPATRIA");
addOption(document.getElementById('city'),"04","EL CENTRO");
addOption(document.getElementById('city'),"05","HOLTVILLE");
addOption(document.getElementById('city'),"06","IMPERIAL");
addOption(document.getElementById('city'),"07","WESTMORLAND");
break;case '14':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","BISHOP");
break;case '15':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","ARVIN");
addOption(document.getElementById('city'),"02","BAKERSFIELD");
addOption(document.getElementById('city'),"03","DELANO");
addOption(document.getElementById('city'),"04","MARICOPA");
addOption(document.getElementById('city'),"05","MCFARLAND");
addOption(document.getElementById('city'),"06","RIDGECREST");
addOption(document.getElementById('city'),"07","SHAFTER");
addOption(document.getElementById('city'),"08","TAFT");
addOption(document.getElementById('city'),"09","TEHACHAPI");
addOption(document.getElementById('city'),"10","WASCO");
addOption(document.getElementById('city'),"11","CALIFORNIA CITY");
addOption(document.getElementById('city'),"12","CSU BAKERSFIELD");
addOption(document.getElementById('city'),"13","CHINA LAKE");
addOption(document.getElementById('city'),"15","BEAR VALLEY SPRINGS");
break;case '16':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","CORCORAN");
addOption(document.getElementById('city'),"02","HANFORD");
addOption(document.getElementById('city'),"03","LEMOORE");
addOption(document.getElementById('city'),"90","AVENAL");
break;case '17':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","LAKEPORT");
addOption(document.getElementById('city'),"02","CLEARLAKE");
break;case '18':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","SUSANVILLE");
break;case '19':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","ALHAMBRA");
addOption(document.getElementById('city'),"02","ARCADIA");
addOption(document.getElementById('city'),"03","ARTESIA");
addOption(document.getElementById('city'),"04","AVALON");
addOption(document.getElementById('city'),"05","AZUSA");
addOption(document.getElementById('city'),"06","BALDWIN PARK");
addOption(document.getElementById('city'),"07","BELL");
addOption(document.getElementById('city'),"08","BELLFLOWER");
addOption(document.getElementById('city'),"09","BELL GARDENS");
addOption(document.getElementById('city'),"10","BEVERLY HILLS");
addOption(document.getElementById('city'),"11","BRADBURY");
addOption(document.getElementById('city'),"12","BURBANK");
addOption(document.getElementById('city'),"13","CLAREMONT");
addOption(document.getElementById('city'),"14","COMMERCE");
addOption(document.getElementById('city'),"15","COMPTON");
addOption(document.getElementById('city'),"16","COVINA");
addOption(document.getElementById('city'),"17","CUDAHY");
addOption(document.getElementById('city'),"18","CULVER CITY");
addOption(document.getElementById('city'),"19","CERRITOS");
addOption(document.getElementById('city'),"20","DOWNEY");
addOption(document.getElementById('city'),"21","DUARTE");
addOption(document.getElementById('city'),"22","EL MONTE");
addOption(document.getElementById('city'),"23","EL SEGUNDO");
addOption(document.getElementById('city'),"24","GARDENA");
addOption(document.getElementById('city'),"25","GLENDALE");
addOption(document.getElementById('city'),"26","GLENDORA");
addOption(document.getElementById('city'),"27","HAWAIIAN GARDENS");
addOption(document.getElementById('city'),"28","HAWTHORNE");
addOption(document.getElementById('city'),"29","HERMOSA BEACH");
addOption(document.getElementById('city'),"30","HIDDEN HILLS");
addOption(document.getElementById('city'),"31","HUNTINGTON PARK");
addOption(document.getElementById('city'),"32","INDUSTRY");
addOption(document.getElementById('city'),"33","INGLEWOOD");
addOption(document.getElementById('city'),"34","IRWINDALE");
addOption(document.getElementById('city'),"35","LAKEWOOD");
addOption(document.getElementById('city'),"36","LA MIRADA");
addOption(document.getElementById('city'),"37","LA PUENTE");
addOption(document.getElementById('city'),"38","LA VERNE");
addOption(document.getElementById('city'),"39","LAWNDALE");
addOption(document.getElementById('city'),"40","LOMITA");
addOption(document.getElementById('city'),"41","LONG BEACH");
addOption(document.getElementById('city'),"42","LOS ANGELES");
addOption(document.getElementById('city'),"43","LYNWOOD");
addOption(document.getElementById('city'),"44","MANHATTAN BEACH");
addOption(document.getElementById('city'),"45","MAYWOOD");
addOption(document.getElementById('city'),"46","MONROVIA");
addOption(document.getElementById('city'),"47","MONTEBELLO");
addOption(document.getElementById('city'),"48","MONTEREY PARK");
addOption(document.getElementById('city'),"49","NORWALK");
addOption(document.getElementById('city'),"50","PALMDALE");
addOption(document.getElementById('city'),"51","PALOS VERDES EST");
addOption(document.getElementById('city'),"52","PARAMOUNT");
addOption(document.getElementById('city'),"53","PASADENA");
addOption(document.getElementById('city'),"54","PICO RIVERA");
addOption(document.getElementById('city'),"55","POMONA");
addOption(document.getElementById('city'),"56","REDONDO BEACH");
addOption(document.getElementById('city'),"57","ROLLING HILLS");
addOption(document.getElementById('city'),"58","ROLLING HILLS EST");
addOption(document.getElementById('city'),"59","ROSEMEAD");
addOption(document.getElementById('city'),"60","SAN DIMAS");
addOption(document.getElementById('city'),"61","SAN FERNANDO");
addOption(document.getElementById('city'),"62","SAN GABRIEL");
addOption(document.getElementById('city'),"63","SAN MARINO");
addOption(document.getElementById('city'),"64","SANTA FE SPRINGS");
addOption(document.getElementById('city'),"65","SANTA MONICA");
addOption(document.getElementById('city'),"66","SIERRA MADRE");
addOption(document.getElementById('city'),"67","SIGNAL HILL");
addOption(document.getElementById('city'),"68","SOUTH EL MONTE");
addOption(document.getElementById('city'),"69","SOUTH GATE");
addOption(document.getElementById('city'),"70","SOUTH PASADENA");
addOption(document.getElementById('city'),"71","TEMPLE CITY");
addOption(document.getElementById('city'),"72","TORRANCE");
addOption(document.getElementById('city'),"73","VERNON");
addOption(document.getElementById('city'),"74","WALNUT");
addOption(document.getElementById('city'),"75","WEST COVINA");
addOption(document.getElementById('city'),"76","WHITTIER");
addOption(document.getElementById('city'),"77","CARSON");
addOption(document.getElementById('city'),"78","CAL POLY POMONA");
addOption(document.getElementById('city'),"79","WEST HOLLYWOOD");
addOption(document.getElementById('city'),"80","RANCHO PALOS VERDES");
addOption(document.getElementById('city'),"81","CSU DOMINGUEZ HILLS");
addOption(document.getElementById('city'),"82","CSU LONG BEACH");
addOption(document.getElementById('city'),"83","CSU LOS ANGELES");
addOption(document.getElementById('city'),"84","CSU NORTHRIDGE");
addOption(document.getElementById('city'),"85","SANTA CLARITA");
addOption(document.getElementById('city'),"88","EL CAMINO COMM CLG");
addOption(document.getElementById('city'),"89","CALABASAS");
addOption(document.getElementById('city'),"90","DIAMOND BAR");
addOption(document.getElementById('city'),"91","LA CANADA-FLINTRIDGE");
addOption(document.getElementById('city'),"92","LANCASTER");
addOption(document.getElementById('city'),"93","WESTLAKE VILLAGE");
addOption(document.getElementById('city'),"94","AGOURA HILLS");
addOption(document.getElementById('city'),"95","MALIBU");
addOption(document.getElementById('city'),"97","UC LOS ANGELES");
addOption(document.getElementById('city'),"99","LA HABRA HEIGHTS");
break;case '20':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","CHOWCHILLA");
addOption(document.getElementById('city'),"02","MADERA");
break;case '21':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","BELVEDERE");
addOption(document.getElementById('city'),"02","CORTE MADERA");
addOption(document.getElementById('city'),"03","FAIRFAX");
addOption(document.getElementById('city'),"04","LARKSPUR");
addOption(document.getElementById('city'),"05","MILL VALLEY");
addOption(document.getElementById('city'),"06","NOVATO");
addOption(document.getElementById('city'),"07","ROSS");
addOption(document.getElementById('city'),"08","SAN ANSELMO");
addOption(document.getElementById('city'),"09","SAN RAFAEL");
addOption(document.getElementById('city'),"10","SAUSALITO");
addOption(document.getElementById('city'),"11","TIBURON");
addOption(document.getElementById('city'),"14","MARIN PARK DIST");
break;case '22':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
break;case '23':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","FORT BRAGG");
addOption(document.getElementById('city'),"02","POINT ARENA");
addOption(document.getElementById('city'),"03","UKIAH");
addOption(document.getElementById('city'),"04","WILLITS");
break;case '24':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","ATWATER");
addOption(document.getElementById('city'),"02","DOS PALOS");
addOption(document.getElementById('city'),"03","GUSTINE");
addOption(document.getElementById('city'),"04","LIVINGSTON");
addOption(document.getElementById('city'),"05","LOS BANOS");
addOption(document.getElementById('city'),"06","MERCED");
addOption(document.getElementById('city'),"10","FOUR RIVERS PK DIST");
break;case '25':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","ALTURAS");
break;case '26':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","MAMMOTH LAKES");
break;case '27':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","CARMEL");
addOption(document.getElementById('city'),"02","DEL REY OAKS");
addOption(document.getElementById('city'),"03","GONZALES");
addOption(document.getElementById('city'),"04","GREENFIELD");
addOption(document.getElementById('city'),"05","KING CITY");
addOption(document.getElementById('city'),"06","MONTEREY");
addOption(document.getElementById('city'),"07","PACIFIC GROVE");
addOption(document.getElementById('city'),"08","SALINAS");
addOption(document.getElementById('city'),"09","SAND CITY");
addOption(document.getElementById('city'),"10","SEASIDE");
addOption(document.getElementById('city'),"11","SOLEDAD");
addOption(document.getElementById('city'),"12","MARINA");
addOption(document.getElementById('city'),"17","MONTEREY PARK DIST");
addOption(document.getElementById('city'),"19","CSU-MONTEREY BAY");
break;case '28':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","CALISTOGA");
addOption(document.getElementById('city'),"02","NAPA");
addOption(document.getElementById('city'),"03","SAINT HELENA");
addOption(document.getElementById('city'),"04","YOUNTVILLE");
addOption(document.getElementById('city'),"05","AMERICAN CANYON");
break;case '29':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","GRASS VALLEY");
addOption(document.getElementById('city'),"02","NEVADA CITY");
addOption(document.getElementById('city'),"08","TRUCKEE");
addOption(document.getElementById('city'),"80","TRUCKEE");
break;case '30':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","ANAHEIM");
addOption(document.getElementById('city'),"02","BREA");
addOption(document.getElementById('city'),"03","BUENA PARK");
addOption(document.getElementById('city'),"04","COSTA MESA");
addOption(document.getElementById('city'),"05","CYPRESS");
addOption(document.getElementById('city'),"06","LA PALMA");
addOption(document.getElementById('city'),"07","FOUNTAIN VALLEY");
addOption(document.getElementById('city'),"08","FULLERTON");
addOption(document.getElementById('city'),"09","GARDEN GROVE");
addOption(document.getElementById('city'),"10","HUNTINGTON BEACH");
addOption(document.getElementById('city'),"11","LAGUNA BEACH");
addOption(document.getElementById('city'),"12","LA HABRA");
addOption(document.getElementById('city'),"13","LOS ALAMITOS");
addOption(document.getElementById('city'),"14","NEWPORT BEACH");
addOption(document.getElementById('city'),"15","ORANGE");
addOption(document.getElementById('city'),"16","PLACENTIA");
addOption(document.getElementById('city'),"17","SAN CLEMENTE");
addOption(document.getElementById('city'),"18","SAN JUAN CAPISTRANO");
addOption(document.getElementById('city'),"19","SANTA ANA");
addOption(document.getElementById('city'),"20","SEAL BEACH");
addOption(document.getElementById('city'),"21","STANTON");
addOption(document.getElementById('city'),"22","TUSTIN");
addOption(document.getElementById('city'),"23","VILLA PARK");
addOption(document.getElementById('city'),"24","WESTMINSTER");
addOption(document.getElementById('city'),"25","YORBA LINDA");
addOption(document.getElementById('city'),"26","IRVINE");
addOption(document.getElementById('city'),"27","CSU FULLERTON");
addOption(document.getElementById('city'),"28","MISSION VIEJO");
addOption(document.getElementById('city'),"29","DANA POINT");
addOption(document.getElementById('city'),"32","ORANGE COAST PK DIST");
addOption(document.getElementById('city'),"40","LAGUNA NIGUEL");
addOption(document.getElementById('city'),"45","LAGUNA HILLS");
addOption(document.getElementById('city'),"48","RCHO SNTA MARGARITA");
addOption(document.getElementById('city'),"49","ALISO VIEJO");
addOption(document.getElementById('city'),"50","LAKE FOREST");
addOption(document.getElementById('city'),"51","LAGUNA WOODS");
addOption(document.getElementById('city'),"97","UC IRVINE");
break;case '31':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","AUBURN");
addOption(document.getElementById('city'),"02","COLFAX");
addOption(document.getElementById('city'),"03","LINCOLN");
addOption(document.getElementById('city'),"04","ROCKLIN");
addOption(document.getElementById('city'),"05","ROSEVILLE");
addOption(document.getElementById('city'),"06","LOOMIS");
addOption(document.getElementById('city'),"07","SIERRA PARK DIST");
addOption(document.getElementById('city'),"11","SIERRA COLLEGE");
break;case '32':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","PORTOLA");
break;case '33':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","BANNING");
addOption(document.getElementById('city'),"02","BEAUMONT");
addOption(document.getElementById('city'),"03","BLYTHE");
addOption(document.getElementById('city'),"05","COACHELLA");
addOption(document.getElementById('city'),"06","DESERT HOT SPRINGS");
addOption(document.getElementById('city'),"07","LAKE ELSINORE");
addOption(document.getElementById('city'),"08","HEMET");
addOption(document.getElementById('city'),"09","INDIO");
addOption(document.getElementById('city'),"10","NORCO");
addOption(document.getElementById('city'),"11","PALM SPRINGS");
addOption(document.getElementById('city'),"12","PERRIS");
addOption(document.getElementById('city'),"13","RIVERSIDE");
addOption(document.getElementById('city'),"14","SAN JACINTO");
addOption(document.getElementById('city'),"15","CORONA");
addOption(document.getElementById('city'),"16","INDIAN WELLS");
addOption(document.getElementById('city'),"17","RANCHO MIRAGE");
addOption(document.getElementById('city'),"18","PALM DESERT");
addOption(document.getElementById('city'),"24","LOS LAGOS PARK DIST");
addOption(document.getElementById('city'),"25","CATHEDRAL CITY");
addOption(document.getElementById('city'),"35","TEMECULA");
addOption(document.getElementById('city'),"36","CALIMESA");
addOption(document.getElementById('city'),"37","CANYON LAKE");
addOption(document.getElementById('city'),"42","MURRIETA");
addOption(document.getElementById('city'),"92","LA QUINTA");
addOption(document.getElementById('city'),"94","MORENO VALLEY");
addOption(document.getElementById('city'),"97","UC RIVERSIDE");
break;case '34':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","FOLSOM");
addOption(document.getElementById('city'),"02","GALT");
addOption(document.getElementById('city'),"03","ISLETON");
addOption(document.getElementById('city'),"04","SACRAMENTO");
addOption(document.getElementById('city'),"08","CSU SACRAMENTO");
addOption(document.getElementById('city'),"12","AMERICAN RIV PK DIST");
addOption(document.getElementById('city'),"22","GOLD RUSH PARK DIST");
addOption(document.getElementById('city'),"33","TWIN CITIES PK DIST");
addOption(document.getElementById('city'),"47","CITRUS HEIGHTS");
addOption(document.getElementById('city'),"50","ELK GROVE");
addOption(document.getElementById('city'),"90","RANCHO CORDOVA");
break;case '35':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","HOLLISTER");
addOption(document.getElementById('city'),"02","SAN JUAN BAUTISTA");
addOption(document.getElementById('city'),"04","HOLLISTER HILLS PARK");
break;case '36':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","BARSTOW");
addOption(document.getElementById('city'),"02","CHINO");
addOption(document.getElementById('city'),"03","COLTON");
addOption(document.getElementById('city'),"04","FONTANA");
addOption(document.getElementById('city'),"05","MONTCLAIR");
addOption(document.getElementById('city'),"06","NEEDLES");
addOption(document.getElementById('city'),"07","ONTARIO");
addOption(document.getElementById('city'),"08","REDLANDS");
addOption(document.getElementById('city'),"09","RIALTO");
addOption(document.getElementById('city'),"10","SAN BERNARDINO");
addOption(document.getElementById('city'),"11","UPLAND");
addOption(document.getElementById('city'),"12","VICTORVILLE");
addOption(document.getElementById('city'),"13","ADELANTO");
addOption(document.getElementById('city'),"14","CSU SAN BERNARDINO");
addOption(document.getElementById('city'),"15","LOMA LINDA");
addOption(document.getElementById('city'),"16","RANCHO CUCAMONGA");
addOption(document.getElementById('city'),"17","TWENTYNINE PALMS");
addOption(document.getElementById('city'),"18","HIGHLAND");
addOption(document.getElementById('city'),"19","HESPERIA");
addOption(document.getElementById('city'),"21","APPLE VALLEY");
addOption(document.getElementById('city'),"30","CHINO HILLS");
addOption(document.getElementById('city'),"31","YUCCA VALLEY");
addOption(document.getElementById('city'),"40","YUCAIPA");
addOption(document.getElementById('city'),"80","BIG BEAR LAKE");
addOption(document.getElementById('city'),"90","GRAND TERRACE");
break;case '37':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","CARLSBAD");
addOption(document.getElementById('city'),"02","CHULA VISTA");
addOption(document.getElementById('city'),"03","CORONADO");
addOption(document.getElementById('city'),"04","DEL MAR");
addOption(document.getElementById('city'),"05","EL CAJON");
addOption(document.getElementById('city'),"06","ESCONDIDO");
addOption(document.getElementById('city'),"07","IMPERIAL BEACH");
addOption(document.getElementById('city'),"08","LA MESA");
addOption(document.getElementById('city'),"09","NATIONAL CITY");
addOption(document.getElementById('city'),"10","OCEANSIDE");
addOption(document.getElementById('city'),"11","SAN DIEGO");
addOption(document.getElementById('city'),"12","SAN MARCOS");
addOption(document.getElementById('city'),"13","VISTA");
addOption(document.getElementById('city'),"14","SAN DIEGO STATE UNIV");
addOption(document.getElementById('city'),"15","SAN DIEGO HARBOR");
addOption(document.getElementById('city'),"20","LEMON GROVE");
addOption(document.getElementById('city'),"22","COLORADO DESERT PARK");
addOption(document.getElementById('city'),"24","OCOTILLO WLS PK DIST");
addOption(document.getElementById('city'),"25","SAN DIEGO PK DIST");
addOption(document.getElementById('city'),"80","POWAY");
addOption(document.getElementById('city'),"81","SANTEE");
addOption(document.getElementById('city'),"82","ENCINITAS");
addOption(document.getElementById('city'),"83","SOLANA BEACH");
addOption(document.getElementById('city'),"97","UC SAN DIEGO");
break;case '38':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","SAN FRANCISCO");
addOption(document.getElementById('city'),"03","SAN FRANCISCO STATE");
addOption(document.getElementById('city'),"97","UC SAN FRANCISCO");
break;case '39':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","ESCALON");
addOption(document.getElementById('city'),"02","LODI");
addOption(document.getElementById('city'),"03","MANTECA");
addOption(document.getElementById('city'),"04","RIPON");
addOption(document.getElementById('city'),"05","STOCKTON");
addOption(document.getElementById('city'),"06","TRACY");
addOption(document.getElementById('city'),"20","LATHROP");
break;case '40':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","ARROYO GRANDE");
addOption(document.getElementById('city'),"02","GROVER BEACH");
addOption(document.getElementById('city'),"03","MORRO BAY");
addOption(document.getElementById('city'),"04","PASO ROBLES");
addOption(document.getElementById('city'),"05","PISMO BEACH");
addOption(document.getElementById('city'),"06","SAN LUIS OBISPO");
addOption(document.getElementById('city'),"07","CAL POLY SLO");
addOption(document.getElementById('city'),"08","ATASCADERO");
addOption(document.getElementById('city'),"12","SAN SIMEON PARK DIST");
addOption(document.getElementById('city'),"13","S L OBISPO CST DIST");
addOption(document.getElementById('city'),"14","PISMO DUNES PK DIST");
break;case '41':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","ATHERTON");
addOption(document.getElementById('city'),"02","BELMONT");
addOption(document.getElementById('city'),"03","BRISBANE");
addOption(document.getElementById('city'),"04","BURLINGAME");
addOption(document.getElementById('city'),"05","COLMA");
addOption(document.getElementById('city'),"06","DALY CITY");
addOption(document.getElementById('city'),"07","HALF MOON BAY");
addOption(document.getElementById('city'),"08","HILLSBOROUGH");
addOption(document.getElementById('city'),"09","MENLO PARK");
addOption(document.getElementById('city'),"10","MILLBRAE");
addOption(document.getElementById('city'),"11","PACIFICA");
addOption(document.getElementById('city'),"12","PORTOLA VALLEY");
addOption(document.getElementById('city'),"13","REDWOOD CITY");
addOption(document.getElementById('city'),"14","SAN BRUNO");
addOption(document.getElementById('city'),"15","SAN CARLOS");
addOption(document.getElementById('city'),"16","SAN MATEO");
addOption(document.getElementById('city'),"17","SOUTH SAN FRANCISCO");
addOption(document.getElementById('city'),"18","WOODSIDE");
addOption(document.getElementById('city'),"19","BROADMOOR");
addOption(document.getElementById('city'),"20","FOSTER CITY");
addOption(document.getElementById('city'),"25","SF INTRNATNL AIRPORT");
addOption(document.getElementById('city'),"26","BAY AREA PARK DIST");
addOption(document.getElementById('city'),"27","EAST PALO ALTO");
break;case '42':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","GUADALUPE");
addOption(document.getElementById('city'),"02","LOMPOC");
addOption(document.getElementById('city'),"03","SANTA BARBARA");
addOption(document.getElementById('city'),"04","SANTA MARIA");
addOption(document.getElementById('city'),"05","CARPINTERIA");
addOption(document.getElementById('city'),"06","SOLVANG");
addOption(document.getElementById('city'),"12","BUELLTON");
addOption(document.getElementById('city'),"14","GOLETA");
addOption(document.getElementById('city'),"97","UC SANTA BARBARA");
break;case '43':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"02","CAMPBELL");
addOption(document.getElementById('city'),"03","CUPERTINO");
addOption(document.getElementById('city'),"04","GILROY");
addOption(document.getElementById('city'),"05","LOS ALTOS");
addOption(document.getElementById('city'),"06","LOS ALTOS HILLS");
addOption(document.getElementById('city'),"07","LOS GATOS");
addOption(document.getElementById('city'),"08","MILPITAS");
addOption(document.getElementById('city'),"09","MONTE SERENO");
addOption(document.getElementById('city'),"10","MORGAN HILL");
addOption(document.getElementById('city'),"11","MOUNTAIN VIEW");
addOption(document.getElementById('city'),"12","PALO ALTO");
addOption(document.getElementById('city'),"13","SAN JOSE");
addOption(document.getElementById('city'),"14","SANTA CLARA");
addOption(document.getElementById('city'),"15","SARATOGA");
addOption(document.getElementById('city'),"16","SUNNYVALE");
addOption(document.getElementById('city'),"17","SAN JOSE STATE UNIV");
addOption(document.getElementById('city'),"20","SJ EVRGREEN COMM CLG");
break;case '44':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","CAPITOLA");
addOption(document.getElementById('city'),"02","SANTA CRUZ");
addOption(document.getElementById('city'),"03","WATSONVILLE");
addOption(document.getElementById('city'),"04","SCOTTS VALLEY");
addOption(document.getElementById('city'),"08","SANTA CRUZ PK DIST");
addOption(document.getElementById('city'),"97","UC SANTA CRUZ");
break;case '45':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","ANDERSON");
addOption(document.getElementById('city'),"02","REDDING");
addOption(document.getElementById('city'),"80","SHASTA LAKE");
break;case '46':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","LOYALTON");
break;case '47':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","DORRIS");
addOption(document.getElementById('city'),"02","DUNSMUIR");
addOption(document.getElementById('city'),"03","ETNA");
addOption(document.getElementById('city'),"04","FORT JONES");
addOption(document.getElementById('city'),"05","MONTAGUE");
addOption(document.getElementById('city'),"06","MOUNT SHASTA");
addOption(document.getElementById('city'),"07","TULELAKE");
addOption(document.getElementById('city'),"08","WEED");
addOption(document.getElementById('city'),"09","YREKA");
addOption(document.getElementById('city'),"10","LAKE SHASTINA");
break;case '48':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","BENICIA");
addOption(document.getElementById('city'),"02","DIXON");
addOption(document.getElementById('city'),"03","FAIRFIELD");
addOption(document.getElementById('city'),"04","RIO VISTA");
addOption(document.getElementById('city'),"05","SUISUN CITY");
addOption(document.getElementById('city'),"06","VACAVILLE");
addOption(document.getElementById('city'),"07","VALLEJO");
break;case '49':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","CLOVERDALE");
addOption(document.getElementById('city'),"02","COTATI");
addOption(document.getElementById('city'),"03","HEALDSBURG");
addOption(document.getElementById('city'),"04","ROHNERT PARK");
addOption(document.getElementById('city'),"05","SANTA ROSA");
addOption(document.getElementById('city'),"06","SEBASTOPOL");
addOption(document.getElementById('city'),"07","SONOMA");
addOption(document.getElementById('city'),"08","PETALUMA");
addOption(document.getElementById('city'),"09","SONOMA STATE UNIV");
addOption(document.getElementById('city'),"11","SILVERADO PARK DIST");
addOption(document.getElementById('city'),"12","RUSS RIV MNDCNO DIST");
addOption(document.getElementById('city'),"14","SANTA ROSA CAMPUS PD");
addOption(document.getElementById('city'),"80","WINDSOR");
break;case '50':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","CERES");
addOption(document.getElementById('city'),"02","MODESTO");
addOption(document.getElementById('city'),"03","NEWMAN");
addOption(document.getElementById('city'),"04","OAKDALE");
addOption(document.getElementById('city'),"05","PATTERSON");
addOption(document.getElementById('city'),"06","RIVERBANK");
addOption(document.getElementById('city'),"07","TURLOCK");
addOption(document.getElementById('city'),"08","WATERFORD");
addOption(document.getElementById('city'),"09","HUGHSON");
addOption(document.getElementById('city'),"10","CSC STANISLAUS");
break;case '51':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","LIVE OAK");
addOption(document.getElementById('city'),"02","YUBA CITY");
break;case '52':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","CORNING");
addOption(document.getElementById('city'),"02","RED BLUFF");
addOption(document.getElementById('city'),"03","TEHAMA");
break;case '53':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
break;case '54':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","DINUBA");
addOption(document.getElementById('city'),"02","EXETER");
addOption(document.getElementById('city'),"03","FARMERSVILLE");
addOption(document.getElementById('city'),"04","LINDSAY");
addOption(document.getElementById('city'),"05","PORTERVILLE");
addOption(document.getElementById('city'),"06","TULARE");
addOption(document.getElementById('city'),"07","VISALIA");
addOption(document.getElementById('city'),"08","WOODLAKE");
break;case '55':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","SONORA");
break;case '56':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","CAMARILLO");
addOption(document.getElementById('city'),"02","FILLMORE");
addOption(document.getElementById('city'),"03","OJAI");
addOption(document.getElementById('city'),"04","OXNARD");
addOption(document.getElementById('city'),"05","PORT HUENEME");
addOption(document.getElementById('city'),"06","SANTA PAULA");
addOption(document.getElementById('city'),"07","THOUSAND OAKS");
addOption(document.getElementById('city'),"08","VENTURA");
addOption(document.getElementById('city'),"09","SIMI VALLEY");
addOption(document.getElementById('city'),"13","ANGELES PARK DIST");
addOption(document.getElementById('city'),"15","CHANNEL CST PK DIST");
addOption(document.getElementById('city'),"17","HUNGRY VLY PK DIST");
addOption(document.getElementById('city'),"90","MOORPARK");
break;case '57':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","DAVIS");
addOption(document.getElementById('city'),"02","WINTERS");
addOption(document.getElementById('city'),"03","WOODLAND");
addOption(document.getElementById('city'),"04","WEST SACRAMENTO");
addOption(document.getElementById('city'),"97","UC DAVIS");
break;case '58':
	removeAllOptions(document.getElementById('city'));
	addOption(document.getElementById('city'),"All", "ALL");
addOption(document.getElementById('city'),"00","UNINCORPORATED");
addOption(document.getElementById('city'),"01","MARYSVILLE");
addOption(document.getElementById('city'),"02","WHEATLAND");
break;
		}
	}
}
function removeAllOptions(selectbox)
{
	var i;
	for(i=selectbox.length-1;i>=0;i--)
	{
		//selectbox.options.remove(i);
		selectbox.remove(i);
	}
}
function addOption(selectbox, value, text )
{
	var optn = document.createElement("OPTION");
	optn.text = text;
	optn.value = value;

	selectbox.options.add(optn);
}